Page D'accueil
WildCodeSchool/level-up-tasks pull request #17
Opened 2024-06-07 01:55 UTC by MoubarkiS

2024-06-07 07:23 UTC, Fatimata-dev approved these changes

2024-06-07 07:27 UTC, Benja-san requested changes

2024-06-07 07:27 UTC, Benja-san commented on src/app/pages/home/home.component.html
> +      <button><a href="#">Inscription</a></button>
wrap your buttons into li tags

2024-06-07 07:27 UTC, Benja-san commented on src/app/pages/home/home.component.html
> +    <h1>Les Fonctionnalités</h1>
only one h1 in this page, use h2 instead

2024-06-07 07:27 UTC, Benja-san commented on src/app/pages/home/home.component.html
> +    <h1>Les Fonctionnalités</h1>
Also this title has its place into the below section, not into the buttons nav

2024-06-07 07:27 UTC, Benja-san commented on src/app/pages/home/home.component.html
> +    <div class="image-container">
ul and li since you'll have a list of 2 cards

2024-06-07 07:27 UTC, Benja-san commented on src/app/pages/home/home.component.html
> +      <div class="image-item">
use article tag instead of div

2024-06-07 09:41 UTC, Benja-san requested changes

2024-06-07 09:41 UTC, Benja-san commented on src/app/pages/home/home.component.html
> +  <article class="content">
no article tag here

2024-06-07 09:41 UTC, Benja-san commented on src/app/pages/home/home.component.html
>          <h3>Créer des taches !</h3>
wrap all your card content into article tag

2024-06-11 13:16 UTC, Benja-san requested changes

2024-06-11 13:16 UTC, Benja-san commented on src/app/app.routes.ts
> +    path: 'signup',
code in english but content in french ?

2024-06-11 14:10 UTC, Benja-san approved these changes

2024-06-11 14:11 UTC, merged