creation of the user-profile page and the profile component
WildCodeSchool/level-up-tasks pull request #23
Opened 2024-06-11 13:47 UTC by Fatimata-dev

creation of the user-profile page and the profile component which is displayed in user-profile for the moment the button is not functional.

2024-06-11 14:23 UTC, LucieLDa requested changes

2024-06-11 14:23 UTC, LucieLDa commented on src/app/model/user/profil.ts
> +        public team: string,
An User can be in multiple different teams.

2024-06-11 14:23 UTC, LucieLDa commented on src/app/model/user/profil.ts
> +export class Profil {
Profil is not a good name for this class, rename to User.

2024-06-11 14:23 UTC, LucieLDa commented on src/app/model/user/profil.ts
> +        public role: string,
An User can be in multiple different teams, it's not a good idea to put role in Profil class since those values will be differrent for each team

2024-06-11 14:23 UTC, LucieLDa commented on src/app/components/profil/profil.component.html
> +   }
Make the Indentation slightly bigger to make the if block more visible.

2024-06-11 14:23 UTC, LucieLDa commented on src/app/components/nav-bar/nav-bar.component.html
>                      <li><a [routerLink]="['/teams']">About us</a></li>
The first two li tags have different indentation compared to the rest of the code.

2024-06-11 14:23 UTC, LucieLDa commented on src/app/model/user/profil.ts
> +        public image: string,
image is a bit vague as a variable name, rename to something like profilImage

2024-06-11 14:23 UTC, LucieLDa commented on src/app/components/profil/profil.component.scss
> +        }
The indentation of button is different from the others, make it match with p and h3.

2024-06-11 15:13 UTC, LucieLDa requested changes
The user/profil name change was only for the class object. The component should still be named profil

2024-06-11 15:13 UTC, LucieLDa commented on src/app/components/user/user.component.html
> +  }
Indentation for the content inside if to make it stand out.

2024-06-11 15:37 UTC, LucieLDa approved these changes

2024-06-12 07:37 UTC, Benja-san requested changes

2024-06-12 07:37 UTC, Benja-san commented on src/app/components/profile/profile.component.ts
> +  modalIsOppen: boolean = false;
isModalOpen

2024-06-12 07:37 UTC, Benja-san commented on src/app/model/user/teams-roles.ts
Well played

2024-06-12 07:37 UTC, Benja-san commented on src/app/model/user/user.ts
> +        public reward: number,
if it refers to reward number please change property for rewardNumber, or we could be confuse thinking that a Reward object could be binded to this property

2024-06-12 07:45 UTC, Benja-san reviewed
Change the rewardNumber into your template when you call it into your html

2024-06-12 08:19 UTC, Benja-san approved these changes

2024-06-12 08:26 UTC, merged