Login/Signup pages and some modifications on home.component.scss
WildCodeSchool/level-up-tasks pull request #24
Opened 2024-06-12 08:43 UTC by MoubarkiS

Page de connexion :
  - Création d'un composant de connexion avec un formulaire contenant les champs "Adresse e-mail" et "Mot de passe".
  - Ajout d'une case à cocher pour afficher ou masquer le mot de passe.
  - Ajout de boutons de navigation "Connexion" et "Inscription" en haut du formulaire.
  - Implémentation de la redirection vers la page d'inscription via le bouton "Inscription".

Page d'inscription :
  - Création d'un composant d'inscription avec un formulaire contenant les champs "Prénom", "Nom", "Adresse e-mail" et "Mot de passe".
  - Ajout de boutons de navigation "Connexion" et "Inscription" en haut du formulaire.
  - Implémentation de la redirection vers la page de connexion via le bouton "Connexion".

Responsive design :
  - Ajout de styles réactifs pour garantir une bonne apparence et une utilisation conviviale sur les appareils mobiles.
 
Home Component scss:
  -Modifications de display en responsive

2024-06-12 09:05 UTC, LucieLDa requested changes

2024-06-12 09:05 UTC, LucieLDa commented on src/app/pages/login/login.component.ts
> +      console.log('Password:', password);
Console.log should not show the user's password and email

2024-06-12 09:05 UTC, LucieLDa commented on src/app/pages/signup/signup.component.ts
> +      console.log('Password:', password);
Console.log should not show user's information

2024-06-12 09:05 UTC, LucieLDa commented on src/app/pages/signup/signup.component.html
> +    <button class="toggle-button" (click)="navigateToLogin()">Connexion</button>
The rest of the project uses routerLink instead of navigateTo

2024-06-12 09:05 UTC, LucieLDa commented on src/app/pages/login/login.component.html
> +    <button class="toggle-button" (click)="navigateToSignup()">Inscription</button>
The rest of the project uses routerLink instead of navigateTo

2024-06-12 14:27 UTC, LucieLDa requested changes

2024-06-12 14:27 UTC, LucieLDa commented on src/app/pages/signup/signup.component.scss
> +  }
Indentation not consistent between div, label and button.

2024-06-12 14:27 UTC, LucieLDa commented on src/app/pages/login/login.component.ts
> +  hidePassword = true;
hidePassword is a bool, naming convention for boolean starts with "is".

2024-06-12 15:16 UTC, LucieLDa approved these changes

2024-06-12 15:23 UTC, Benja-san requested changes

2024-06-12 15:23 UTC, Benja-san commented on src/app/app.module.ts
why d'you add an app module ?

2024-06-12 15:23 UTC, Benja-san commented on src/app/app.routes.ts
> +  { path: 'motdepasseoublie',
use hyphen for prettier urls

2024-06-12 15:23 UTC, Benja-san commented on src/app/pages/signup/signup.component.ts
> +  passwordMatchValidator(form: FormGroup) {
nice method but you don't have any confirm password field ?

2024-06-12 15:24 UTC, Benja-san commented
Keep in mind to add error message display for this US !

2024-06-12 23:13 UTC, MoubarkiS commented on src/app/app.module.ts
i used the app module for the navigateto and for the module of routes, should i keep it like a comment or delete it ?

2024-06-13 12:37 UTC, Benja-san requested changes

2024-06-13 12:37 UTC, Benja-san commented on src/app/pages/signup/signup.component.ts
> +      console.log('User registered');
remove console logs

2024-06-13 12:37 UTC, Benja-san commented on src/app/pages/signup/signup.component.ts
> +      console.log('Form is invalid');
remove console logs

2024-06-13 14:14 UTC, Benja-san approved these changes

2024-06-13 15:13 UTC, merged