User profil
WildCodeSchool/level-up-tasks pull request #25
Opened 2024-06-12 15:46 UTC by Fatimata-dev

using modal to edit user profile(image firstname and lastname)
I hide the input to select the image and I put a pen instead of clicking this one will trigger a click for the input then we can select an image(scss)

2024-06-12 18:02 UTC, LucieLDa requested changes

2024-06-12 18:02 UTC, LucieLDa commented on src/app/components/profile/profile.component.html
> +  <form #edditUserform="ngForm" (ngSubmit)="editUser()">
Spelling error with #edditUserform, should change to #editUserForm

2024-06-13 07:14 UTC, LucieLDa approved these changes

2024-06-13 07:47 UTC, Benja-san reviewed
refactor file input spoofing
rename reward number into rewarPercentage

2024-06-13 08:59 UTC, Benja-san approved these changes

2024-06-13 08:59 UTC, Benja-san commented on src/app/components/profile/profile.component.ts
>    //Use the ViewChild directive to access the fileInput DOM element referenced in the HTML template.
remove dead code if useless

2024-06-13 09:00 UTC, merged