Expedition
WildCodeSchool/level-up-tasks pull request #39
Opened 2024-06-20 14:34 UTC by LucieLDa

Add Expedition Object
this object has a title and id
Update Task Object
Task now has an expedition id 
Update Task List Component
This component is now used as an expedition and is repeated in task page
Moved Filter Component to Task Page Component
Various other fixes to accommodate new fontionality

2024-06-20 14:40 UTC, sirinebettaieb approved these changes

2024-06-21 08:27 UTC, Benja-san requested changes

2024-06-21 08:27 UTC, Benja-san commented on src/app/components/add-expedition/add-expedition.component.html
> +    <label>Ajouter une expédition</label>
title more than label

2024-06-21 08:27 UTC, Benja-san commented on src/app/components/add-expedition/add-expedition.component.ts
> +  autogrow(){
if you are using this method in other components, consider shifting it in a service component

2024-06-21 08:32 UTC, Benja-san approved these changes

2024-06-21 08:33 UTC, merged