front-to-back connection with user login and registration
WildCodeSchool/level-up-tasks pull request #43
Opened 2024-06-26 14:32 UTC by Fatimata-dev

creation of a user service, implementation of methods to be able to register or connect a user by calling the back-end then implementation of these methods in the components (signup, login and profile)

2024-06-26 15:25 UTC, MoubarkiS approved these changes
Clean code

2024-06-26 15:45 UTC, Benja-san requested changes
Consider registering the user inside local storage or at least inside a subject available all along navigation. Or else you'll loose the user as soon as you quit your profile page

2024-06-26 15:45 UTC, Benja-san commented on src/app/app.module.ts
Do you really need this app module file ?

2024-06-27 10:54 UTC, Fatimata-dev commented
Saves the information of the logged in user in localstorage then displays links in the nav-bar depending on the state of the user logged in or not

2024-06-27 13:08 UTC, Benja-san approved these changes
Don't forget to finish this us with the update and debug (I'll probably get time this afternoon or Monday)

2024-06-27 13:14 UTC, merged