implement user group in the userprofil
WildCodeSchool/level-up-tasks pull request #44
Opened 2024-06-27 12:48 UTC by sirinebettaieb

Implement userGroup component in the profile page 
create groups and  that allow editing of groups that are displayed as avatars and name of groups

2024-06-27 13:20 UTC, MoubarkiS approved these changes

2024-06-27 14:14 UTC, Benja-san requested changes

2024-06-27 14:14 UTC, Benja-san commented on src/app/components/create-group-dialog/create-group-dialog.component.html
> +<h1 mat-dialog-title>Créer un groupe</h1>
if it is a component, then it is injected inside a page so it won't be a H1 but h2 or higher number

2024-06-27 14:14 UTC, Benja-san commented on src/app/components/edit-group-dialog/edit-group-dialog.component.html
> +<h1 mat-dialog-title>Éditer le groupe</h1>
same here

2024-06-27 14:14 UTC, Benja-san commented on src/app/components/user-groupe/user-groupe.component.html
> +    <h1>Groupes</h1>
same here

2024-06-27 14:14 UTC, Benja-san commented on src/app/model/groupes/groupe.ts
Create a model for each one of those

2024-06-27 14:14 UTC, Benja-san commented on src/app/service/group.service.ts
> +    return of();
you don't have to return an observable if you just delete a User

2024-06-28 07:03 UTC, Benja-san requested changes

2024-06-28 07:03 UTC, Benja-san commented on src/app/model/groupes/groupe.ts
use class over interface

2024-06-28 07:03 UTC, Benja-san commented on src/app/model/membres/membre.ts
> +export interface Member {
here too

2024-06-28 07:46 UTC, Benja-san approved these changes

2024-06-28 07:47 UTC, merged