Jwt token
WildCodeSchool/level-up-tasks pull request #55
Opened 2024-07-09 13:26 UTC by Fatimata-dev

Use of the token to manage a user's connection and protect routes depending on the state of the user connected or not

2024-07-09 13:45 UTC, LucieLDa requested changes

2024-07-09 13:45 UTC, LucieLDa commented on src/app/components/add-expedition/add-expedition.component.ts
> +  //user = this.authService.getUser();
dead code

2024-07-09 13:45 UTC, LucieLDa commented on src/app/components/sidebar/sidebar.component.ts
> +    //this.user = this.authService.getUser();
dead code

2024-07-09 13:45 UTC, LucieLDa commented on src/assets/pictures/clock-icon.png
Clock-icon is not longer used in this project, it was replaced by a font awesome icon

2024-07-09 14:14 UTC, LucieLDa approved these changes

2024-07-09 16:56 UTC, Benja-san requested changes

2024-07-09 16:56 UTC, Benja-san commented on src/app/components/add-expedition/add-expedition.component.ts
> +  userInfo:any ;
if id only id is needed, use number type and retrieve the id directly

2024-07-09 16:56 UTC, Benja-san commented on src/app/app.routes.ts
> +    path:'profile/:id',
keep profil for french content

2024-07-09 16:56 UTC, Benja-san commented on src/app/components/add-expedition/add-expedition.component.ts
> +  user!:User;
are you sure to retrieve a user ?

2024-07-09 16:56 UTC, Benja-san commented on src/app/components/nav-bar/nav-bar.component.ts
> +  userInfo: any = {};
same here

2024-07-09 16:56 UTC, Benja-san commented on src/app/components/sidebar/sidebar.component.ts
> +  userInfo:any;
same here

2024-07-09 16:56 UTC, Benja-san commented on src/app/pages/login/login.component.ts
> +  token: any = {};
use type or model for token

2024-07-09 16:56 UTC, Benja-san commented on src/app/pages/task-page/task-page.component.ts
> +      this.expeditionService.addExpedition(event, this.userInfo.id || 0).subscribe((ex) => {
why or 0 ?

2024-07-10 08:30 UTC, Benja-san approved these changes

2024-07-10 08:33 UTC, merged