Delete expedition
WildCodeSchool/level-up-tasks pull request #56
Opened 2024-07-09 15:31 UTC by Fatimata-dev

2024-07-09 15:36 UTC, LucieLDa approved these changes

2024-07-10 08:36 UTC, Benja-san requested changes

2024-07-10 08:36 UTC, Benja-san commented on src/app/components/add-expedition/add-expedition.component.ts
> +  userInfo:any ;
use id rather than any type (and useless stored data)

2024-07-10 08:36 UTC, Benja-san commented on src/app/components/add-expedition/add-expedition.component.ts
> +  userInfo:any ;
or if you need it in template use a least type for userInfo

2024-07-10 08:36 UTC, Benja-san commented on src/app/components/nav-bar/nav-bar.component.ts
> +  userInfo: any = {};
same here

2024-07-10 08:36 UTC, Benja-san commented on src/app/components/sidebar/sidebar.component.ts
> +  userInfo:any;
ur using this userinfo everywhere, define a model it would be easier to understand which data  are in it

2024-07-10 08:36 UTC, Benja-san commented on src/app/service/User/token.service.ts
> +        id: decodedToken.user_id
can easily be transformed into a type to export

2024-07-10 09:11 UTC, Benja-san approved these changes

2024-07-10 09:11 UTC, merged