Front to back group
WildCodeSchool/level-up-tasks pull request #57
Opened 2024-07-09 16:58 UTC by sirinebettaieb

Connecting the backend and frontend of Group

2024-07-09 17:23 UTC, Fatimata-dev approved these changes

2024-07-10 08:26 UTC, Benja-san requested changes

2024-07-10 08:26 UTC, Benja-san commented on src/app/components/edit-group-dialog/edit-group-dialog.component.ts
> +   console.log(this.data.group)
remove console log

2024-07-10 08:26 UTC, Benja-san commented on src/app/components/edit-group-dialog/edit-group-dialog.component.ts
> +        console.log(group);
remove console log

2024-07-10 08:36 UTC, Benja-san approved these changes

2024-07-10 08:40 UTC, merged